/* DO NOT EDIT THIS FILE - it is machine generated */
#ifndef FaceJNI
#define FaceJNI
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MainEntry */

#ifndef _Included_MainEntry
#define _Included_MainEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MainEntry
 * Method:    TrainFaceData
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jint JNICALL Java_MainEntry_TrainFaceData
  (JNIEnv *, jclass, jstring, jstring,jstring,jstring,jstring);

JNIEXPORT jstring JNICALL Java_MainEntry_RecognizeFace
  (JNIEnv *, jclass, jstring,jstring,jstring );
#ifdef __cplusplus
}
#endif
#endif
#endif
